### ISSUE TITLE
HTMLTableCellElement missing property pages

### ISSUE THREAD

**Issue by manngo** [mdn/content#15631]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/HTMLTableCellElement

### What specific section or headline is this issue about?

Browser Compatibility

### What information was incorrect, unhelpful, or incomplete?

The links appear to be broken. That includes the link for `cellIndex` which is the one I was looking for.

### What did you expect to see?

Working links?

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/htmltablecellelement`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLTableCellElement
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/htmltablecellelement/index.md
* Last commit: https://github.com/mdn/content/commit/e9d054bed500fbfb003c8ca31758afe577f43e31
* Document last modified: 2022-01-21T19:13:55.000Z

</details>

**Comment by hamishwillee** [comment]
Yes, there are many undocumented APIs - they are red to indicate that the documentation has not been written, and to encourage users to contribute them.

If someone takes this on, the deprecated APIs are probably not worth documenting - those links could just be turned into non-link text.

**Comment by janbrasna** [comment]
While the `{{domxref}}` links throughout the page itself are indeed red (and disabled), the OP probably describes issue with the same links being active in `{{Compat}}` and leading to 404s from there.

I believe this is an issue with https://github.com/mdn/browser-compat-data/blob/main/api/HTMLTableCellElement.json#L99 providing links to nonexistent content, and should be therefore fixed there?

**Comment by manngo** [comment]
I don’t think `cellIndex` is deprecated, and there’s no suggestion in the documentation that it is.

I would be happy to contribute what I can, but I can’t find a definitive reference to back up my understanding. ["cellindex" | Can I use](https://caniuse.com/?search=cellindex) indicates full compatibility, but refers back to here.

I would appreciate any help in finding a documented standard for this.

**Comment by sideshowbarker** [comment]
> I would appreciate any help in finding a documented standard for this.

https://html.spec.whatwg.org/multipage/tables.html#dom-tdth-cellindex-dev has this:

> Returns the position of the cell in the row's [`cells`](https://html.spec.whatwg.org/multipage/tables.html#dom-tr-cells) list. This does not necessarily correspond to the x-position of the cell in the table, since earlier cells might cover multiple rows or columns.
>
> Returns −1 if the element isn't in a row.

**Comment by Josh-Cena** [comment]
This is fixed now

**Comment by janbrasna** [comment]
I'm not sure, maybe for the `cellIndex` used as an example — but generally the compatibility tables still don't mark the not-yet-published content "red" as missing.

Take e.g. https://developer.mozilla.org/en-US/docs/Web/API/HTMLTableCellElement#browser_compatibility row "`axis`" or "`height`" — that link still seems to lead somewhere, but ends up 404ing.

I actually think the issue is more "meta" than this specific example. What works for non-existent `{{domxref}}` links within pages doesn't mark the 404ing links the same way in `{{Compat}}` tables.

**Comment by Josh-Cena** [comment]
@janbrasna you are right; but those are deprecated properties and it probably doesn't make sense to write separate pages for them. Since they have corresponding broken `domxref`s, it means we'll still keep track of this flaw and fix it when we fix broken links, but there's no pending documentation work.
