### ISSUE TITLE
Shouldn't All the Required Fields have  required="true" on Them

### ISSUE THREAD

**Issue by jfc3-dol** [mdn/content#26790]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Forms/How_to_structure_a_web_form

### What specific section or headline is this issue about?

Active learning: building a form structure

### What information was incorrect, unhelpful, or incomplete?

Shouldn't all the required INPUT fields on this page have **required="true"** on them.

```
<p>
    <label for="number">
      <span>Card number:</span>
      <strong><span **aria-label="required"**>*</span></strong>
    </label>
    <input type="tel" id="number" name="cardnumber" />
  </p>
```

One of the examples of a required field that does not is the **cardnumber** field.

NOTE - you likely will need to make the same changes to any example page/code from this page or some of the other pages/code in this section.

### What did you expect to see?

I would expect nay required INPUT field to have **required="true"** on them if they are tagged as required with an asterisk and/or **aria-label="required"**.

### Do you have any supporting links, references, or citations?

No, since it's likely a mistake when creating the examples.

### Do you have anything more you want to share?

Nope.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/forms/how_to_structure_a_web_form`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Forms/How_to_structure_a_web_form
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/forms/how_to_structure_a_web_form/index.md
* Last commit: https://github.com/mdn/content/commit/8e2641ebe076ab89299c77a51ece882de4ba5efb
* Document last modified: 2023-02-23T23:55:46.000Z

</details>

**Comment by CBID2** [comment]
I can work on this issue @jfc3-do! :)

**Comment by jfc3-dol** [comment]
Thanks, @CBID2. It's likely more extensive than I thought with all the examples and the example pages for this page that probably need checking and fixing.

Good luck.

**Comment by CBID2** [comment]
Hey @jfc3-dol! I found some evidence that supports your issue. Here it is: https://www.w3.org/TR/WCAG20-TECHS/ARIA2.html

**Comment by minimalsm** [comment]
Hey folks!

I don't think this is a mistake. The required attribute isn't included here because the MDN learning area uses "layered instruction"—a way to introduce new concepts or skills by building upon what the learner already knows and can do, gradually introducing more complex ideas as the learner becomes more proficient. This strategy helps avoid overwhelming the learner with too much information.

The reader has only been introduced to forms in this specific example, so we should keep things simple. They'll be introduced to [optional form controls in the UI pseudo-classes lesson](https://developer.mozilla.org/en-US/docs/Learn/Forms/UI_pseudo-classes#what_pseudo-classes_do_we_have_available).

**Comment by minimalsm** [comment]
Hey @CBID2,

I'm not sure. I don't maintain this project, just giving my opinion. I'd wait for a maintainer to weigh in 😊

**Comment by hamishwillee** [comment]
Yes, this should be fixed. 

You might argue that this is not necessary for demonstrating the use of a form, or that MDN uses a layered approach, so showing how to make a field required at this point is not necessary, and that would be reasonable  (though I think if you use a credit card as an example, then being as close to "real use" as possible is desirable. 

The reason that this is a bug IMO is that we have already made the decision that these should be required by adding the aria label. Given that, choosing not to actually make them required is confusing.

The action is to add `required="true"` to any field that should be required, and make sure there are corresponding aria markup for those same case.
The associated example should be updated in tandem, and merged at the same time: https://github.com/mdn/learning-area/blob/main/html/forms/html-form-structure/payment-form.html

**Comment by CBID2** [comment]
> Yes, this should be fixed.
> 
> You might argue that this is not necessary for demonstrating the use of a form, or that MDN uses a layered approach, so showing how to make a field required at this point is not necessary, and that would be reasonable (though I think if you use a credit card as an example, then being as close to "real use" as possible is desirable.
> 
> The reason that this is a bug IMO is that we have already made the decision that these should be required by adding the aria label. Given that, choosing not to actually make them required is confusing.
> 
> The action is to add `required="true"` to any field that should be required, and make sure there are corresponding aria markup for those same case. The associated example should be updated in tandem, and merged at the same time: https://github.com/mdn/learning-area/blob/main/html/forms/html-form-structure/payment-form.html

Done @hamishwillee
PR #1: [27035](https://github.com/mdn/content/pull/27035) 
PR #2: [628](https://github.com/mdn/learning-area/pull/628)

**Comment by hamishwillee** [comment]
@CBID2 It is not quite fixed.
- #27035 is invalid.
- I think https://github.com/mdn/learning-area/pull/628 looks good but have a question about the correct aria tags to use - see [aria-label="required"](https://github.com/mdn/learning-area/pull/628/files#r1217294027)
- But then we still need to make sure that this and the docs match in https://developer.mozilla.org/en-US/docs/Learn/Forms/How_to_structure_a_web_form#active_learning_building_a_form_structure

**Comment by hamishwillee** [comment]
So confirmed that https://github.com/mdn/learning-area/pull/628

So the final job is to create a docs PR that makes the example look like https://github.com/mdn/learning-area/pull/628

Thanks @CBID2

**Comment by CBID2** [comment]
> So confirmed that [mdn/learning-area#628](https://github.com/mdn/learning-area/pull/628)
> 
> So the final job is to create a docs PR that makes the example look like [mdn/learning-area#628](https://github.com/mdn/learning-area/pull/628)
> 
> Thanks @CBID2

Hey @hamishwillee! Where should I create this new docs pr?

**Comment by hamishwillee** [comment]
@CBID2 Yes, in https://developer.mozilla.org/en-US/docs/Learn/Forms/How_to_structure_a_web_form#active_learning_building_a_form_structure

**Comment by hamishwillee** [comment]
This will be fixed by #27395 and https://github.com/mdn/learning-area/pull/628

**Comment by hamishwillee** [comment]
All done. Thanks @CBID2 @ @jfc3-dol
