### ISSUE TITLE
Response headers are not request headers

### ISSUE THREAD

**Issue by verhovsky** [mdn/content#41843]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Permissions-Policy

### What specific section or headline is this issue about?

The table that says "Header type: Response header, Forbidden request header: yes"

### What information was incorrect, unhelpful, or incomplete?

A "Response header" can't be a "Forbidden request header" because it's not a request header.

### What did you expect to see?

"Forbidden response header: yes"

All response headers need to be changed. Headers that are both request and response headers should ideally be changed too to just be "Forbidden header".

### Do you have anything more you want to share?

https://github.com/mdn/content/pull/38296

`Permissions-Policy` is, it seems to me, [not actually forbidden](https://fetch.spec.whatwg.org/#forbidden-response-header-name) either.

**Comment by hamishwillee** [comment]
Good catch thanks. Fixed by #41938

**Comment by verhovsky** [comment]
This was not fixed. It still says it's a "forbidden request header" when it's a "response header".

**Comment by hamishwillee** [comment]
Have you looked at the PR https://github.com/mdn/content/pull/41938/files ?

If you are looking at the live documents, they can take some time to update.

**Comment by verhovsky** [comment]
But you updated one header I gave as an example, I'm talking about all response headers

**Comment by hamishwillee** [comment]
Indeed, which were fixed in https://github.com/mdn/content/pull/41946. Sorry I didn't make that clear.
