### ISSUE TITLE
Issue with "scroll-margin": Firefox (at least) 70 to 89 have a bug

### ISSUE THREAD

**Issue by dns2utf8** [mdn/content#4770]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-margin

#### What information was incorrect, unhelpful, or incomplete?
The calculation of wether to jump or not and how far is not correct in the current firefox desktop and android.

#### Specific section or headline?
Calling element.focus() on an element that is near the viewbox yields wrong results.

#### What did you expect to see?
Calling element.focus() must always bring at least part of element into the viewbox.

#### Did you test this? If so, how?
* I made a minimal test case: https://data.estada.ch/firefox_scroll-margin_bug/
* Then I filed a but https://bugzilla.mozilla.org/show_bug.cgi?id=1708303

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/scroll-margin`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-margin
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/scroll-margin/index.html
* Last commit: https://github.com/mdn/content/commit/f4fb4c2d90a134366c280eec6cb599825981ad5d
* Document last modified: 2021-03-15T17:55:56.000Z

</details>

**Comment by rachelandrew** [comment]
@dns2utf8 thanks for reporting this, I think if we are going to cover this in the docs then BCD is the correct place especially given this has been fixed, so I'll close this here.

**Comment by dns2utf8** [comment]
Well, it is still broken now. It took me hours to find the solution and when I checked on https://caniuse.com/?search=scroll-margin it displays it as fully functional which is not true.
Bugs in other browsers are listed too. And I was hoping to use scroll-margin now since apple fixed the safaris, but firefox is still blocking the feature.

**Comment by dns2utf8** [comment]
Forgive me, I am not 100% sure I understand.
Are you saying that my PR https://github.com/mdn/browser-compat-data/pull/10346 or somebody else will add that information to the BCD (I assume it is the repo I opened a PR to) and add the information?

**Comment by rachelandrew** [comment]
@dns2utf8 that's right. I don't review those PRs but once that is merged the info will be included in the compat table at the bottom of the page (and anywhere else that uses that compat info). There is no need to do anything to the docs as they include those tables.
