### ISSUE TITLE
Issue with "About MDN Web Docs": unreplaced template markup

### ISSUE THREAD

**Issue by samlh** [mdn/content#510]
MDN URL: https://developer.mozilla.org/en-US/docs/MDN/About

#### What information was incorrect, unhelpful, or incomplete?

Unreplaced template at the top of the page:

>**{{IncludeSubNav("/en-US/docs/MDN")}}**
>MDN Web Docs (previously known as MDN — the Mozilla Developer Network) is an evolving learning platform for Web technologies and the software that powers the Web, including CSS, HTML, and JavaScript. We also have a detailed set of beginner's learning material — see Learn Web development.

#### Specific section or headline?

The very top of the page

#### What did you expect to see?

No templating markup

#### Did you test this? If so, how?

No

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mdn/about`
* MDN URL: https://developer.mozilla.org/en-US/docs/MDN/About
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/mdn/about/index.html
* Report started: 2020-12-21T04:33:59.468Z

</details>

**Comment by sideshowbarker** [comment]
Thanks for reporting this. It’s already fixed in the sources here, by #210. So it’ll get deployed to the production site soon. So OK if we close this?

**Comment by vkWeb** [comment]
@sideshowbarker it looks to me that on #210 we didn't fix the page @samlh has issue with? Maybe we should do a second round of search and replace?

**Comment by sideshowbarker** [comment]
> @sideshowbarker it looks to me that on #210 we didn't fix the page @samlh has issue with? Maybe we should do a second round of search and replace?

Indeed you’re right — thanks for having taken time to check that. I raised #512 with a fix; recursive grep says that file is in fact the only one which still had that macro call.
